/* TYPE CART CONTEXT */
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const DECREASE_QUANTITY_PRODUCT = 'DECREASE_QUANTITY_PRODUCT';
export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const TOTAL_CART = 'TOTAL_CART';
